name:                curl
version:             0.1.0.0
github:              "semenov-vladyslav/curl"
license:             BSD3
author:              "Vlad Semenov"
maintainer:          "semenov.vlad.by@gmail.com"
copyright:           "2019 Vlad Semenov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/curl#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  curl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
